//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreetingCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardInfo
    {
        public CardInfo()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public int Category { get; set; }
        public string Description { get; set; }
        public string ImageFront { get; set; }
        public string ImageBack { get; set; }
    
        public virtual CardCategory CardCategory { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
